# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth0', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idtoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='IdToken',
        ),
    ]
