# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 00:09
from __future__ import unicode_literals

from django.db import migrations


def fix_replies(apps, schema_editor):
    """Adds 'In reply to url: ' to beginning of all replies"""
    Status = apps.get_model('status', 'Status')

    replies = Status.objects.filter(reply_to__isnull=False)
    for reply in replies:
        content = reply.content
        content = 'In reply to https://www.standu.ps/status/%d/:\n%s' % (
            reply.reply_to.id,
            reply.content
        )
        reply.content = content
        reply.save()


def noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0016_restore_teamuser'),
    ]

    operations = [
        migrations.RunPython(fix_replies, noop)
    ]
