# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 17:22
from __future__ import unicode_literals

from django.db import migrations


def fix_replies(apps, schema_editor):
    """Adds 'In reply to url: ' to beginning of all replies"""
    Status = apps.get_model('status', 'Status')

    replies = Status.objects.filter(content__startswith='In reply to ')
    for reply in replies:
        if '\n' not in reply.content:
            print('skipping')
            continue

        firstline, rest = reply.content.split('\n', 1)

        # Pull off the status url
        firstline = firstline.split(' ')
        url = firstline[-1]
        url = url[:-1]

        # url looks like "https://www.standu.ps/status/1614/"
        status_id = url.split('/')[-2]

        # Reassemble first line
        firstline[-1] = '%s [%s]:' % (
            status_id,
            url
        )
        firstline = ' '.join(firstline)
        content = firstline + '\n' + rest
        reply.content = content
        reply.save()


def noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0018_remove_status_reply_to'),
    ]

    operations = [
        migrations.RunPython(fix_replies, noop)
    ]
