# Generated by Django 2.0.2 on 2018-02-09 16:25

from django.db import migrations


def fwds(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')

    Permission.objects.filter(app_label='soapbox').delete()
    ContentType.objects.filter(app_label='soapbox').delete()


def bkwds(apps, schema_editor):
    # No going back
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0019_fix-reply-migration'),
    ]

    operations = [
        # Drop the table
        migrations.RunSQL("""
        DROP TABLE IF EXISTS soapbox_message
        """),

        # Fix content types and permissions
        migrations.RunPython(fwds, bkwds)
    ]
