# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-07 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0020_auto_20180209_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='statuses', to='status.Project'),
        ),
        migrations.AlterField(
            model_name='status',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='status.StandupUser'),
        ),
    ]
