# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-07 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0021_auto_20180607_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Site message; supports markdown')),
                ('enabled', models.BooleanField(default=True, help_text='Whether or not this message is enabled')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, help_text='When this message was created')),
            ],
        ),
    ]
