# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-07 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0022_sitemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemessage',
            name='message',
            field=models.TextField(help_text='Site message'),
        ),
    ]
